# Generated by Django 6.0.6 on 2026-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_user_is_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_logged_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_first_login',
        ),
        migrations.AddField(
            model_name='media',
            name='file_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
