# Generated by Django 6.0.6 on 2026-06-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
    ]
