# Generated by Django 6.0.6 on 2026-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='media_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
